# Helm Chart for MCP Server
apiVersion: v2
name: mcp-server
description: FastMCP Server for Enterprise Requirements Management with Traceability Analytics
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - mcp
  - requirements-management
  - traceability
  - analytics
  - fastapi

maintainers:
  - name: MCP DevOps Team
    email: devops@mcp.com

sources:
  - https://github.com/your-org/mcp-server

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "23.3.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.60.4"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled

annotations:
  category: Analytics
  licenses: MIT